name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          echo "CSV_URL: $CSV_URL"
          echo "TARGET_VAR: $TARGET_VAR"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f MLProject/requirements.txt ]; then pip install -r MLProject/requirements.txt; fi

      - name: Run mlflow project
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/rudywijayaa/Eksperimen_SML_Preprocessing_Rudy-Wijaya.mlflow
          MLFLOW_TRACKING_USERNAME: rudywijayaa
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run ./MLProject --env-manager=local

      - name: Get Latest MLflow Run ID
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/rudywijayaa/Eksperimen_SML_Preprocessing_Rudy-Wijaya.mlflow
          MLFLOW_TRACKING_USERNAME: rudywijayaa
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Ambil Run ID terbaru dari eksperimen
          RUN_ID=$(python -c "import mlflow; exp = mlflow.get_experiment_by_name('Baseline_Model_Churn'); runs = mlflow.search_runs(experiment_ids=[exp.experiment_id]); print(runs.iloc[0]['run_id'])")
          echo "Latest Run ID: $RUN_ID"

          # Simpan ke GITHUB_ENV agar bisa dipakai step selanjutnya
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          pip install skops joblib

      - name: Upload to Google Drive
        run: |
          echo "Proses upload/backup selesai."

      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/rudywijayaa/Eksperimen_SML_Preprocessing_Rudy-Wijaya.mlflow
          MLFLOW_TRACKING_USERNAME: rudywijayaa
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # 1. Download artifact 'model' ke folder lokal menggunakan Python
          python -c "
          import os, dagshub, mlflow
          dagshub.init(repo_owner='rudywijayaa', repo_name='Eksperimen_SML_Preprocessing_Rudy-Wijaya', mlflow=True)
          run_id = os.getenv('RUN_ID')
          print(f'Mengunduh artifact model untuk RUN_ID: {run_id}')
          mlflow.artifacts.download_artifacts(run_id=run_id, artifact_path='model', dst_path='./downloaded_model')
          "

          # 2. Build Docker dari folder lokal yang sudah terunduh
          mlflow models build-docker --model-uri "./downloaded_model" --name "churn-prediction-model"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag churn-prediction-model ${{ secrets.DOCKER_HUB_USERNAME }}/churn-prediction-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/churn-prediction-model:latest
