name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: 'MLProject/churn_preprocessing/X_train.csv'
  TARGET_VAR: 'Exited'
  MLFLOW_TRACKING_URI: 'https://dagshub.com/rudywijayaa/Eksperimen_SML_Preprocessing_Rudy-Wijaya.mlflow'
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_TOKEN }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          echo "CSV_URL: $CSV_URL"
          echo "TARGET_VAR: $TARGET_VAR"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub scikit-learn pandas matplotlib seaborn joblib skops

      - name: Run mlflow project
        run: |
          mlflow run ./MLProject --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          python -c "
          import mlflow, os
          mlflow.set_tracking_uri(os.getenv('MLFLOW_TRACKING_URI'))
          exp = mlflow.get_experiment_by_name('Baseline_Model_Churn')
          if exp:
              runs = mlflow.search_runs(
                  experiment_ids=[exp.experiment_id],
                  filter_string=\"attributes.status = 'FINISHED'\",
                  order_by=['start_time DESC'],
                  max_results=1
              )
              if not runs.empty:
                  run_id = runs.iloc[0]['run_id']
                  print(f'Latest FINISHED Run ID: {run_id}')
                  with open(os.environ['GITHUB_ENV'], 'a') as f:
                      f.write(f'RUN_ID={run_id}\n')
              else:
                  raise Exception('Tidak ditemukan RUN dengan status FINISHED!')
          "

      - name: Install Python dependencies
        run: |
          pip install skops joblib

      - name: Upload to Google Drive
        run: |
          echo "Proses upload/backup selesai."

      - name: Build Docker Model
        run: |
          python -c "
          import os, dagshub, mlflow
          dagshub.init(repo_owner='rudywijayaa', repo_name='Eksperimen_SML_Preprocessing_Rudy-Wijaya', mlflow=True)
          run_id = os.environ['RUN_ID']
          print(f'Mengunduh artefak model untuk RUN_ID: {run_id}')
          mlflow.artifacts.download_artifacts(artifact_uri=f'runs:/{run_id}/model', dst_path='./downloaded_model')
          "
          mlflow models build-docker --model-uri "./downloaded_model" --name "churn-prediction-model"

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: |
          docker tag churn-prediction-model ${{ secrets.DOCKER_HUB_USERNAME }}/churn-prediction-model:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/churn-prediction-model:latest
